from enum import Enum


class CellType(Enum):
    """
    Memory types supported for modeling
    """
    STT = "STT"
    PCM = "PCM"
    FeFET = "FeFET"
    RRAM = "RRAM"
    SRAM = "SRAM"


class OpTarget(Enum):
    """
    Optimization targets for cell configuration
    (see NVSim documentation for further details)
    """
    ReadLatency = "ReadLatency"
    WriteLatency = "WriteLatency"
    ReadDynamicEnergy = "ReadDynamicEnergy"
    WriteDynamicEnergy = "WriteDynamicEnergy"
    ReadEDP = "ReadEDP"
    WriteEDP = "WriteEDP"
    LeakagePower = "LeakagePower"
    Area = "Area"
    Exploration = "Exploration"


class ResultType(Enum):
    """
    Types of results available from model.
    Corresponds to column names in nvmexplorer output datasets.
    """
    MEM_CELL_TYPE = "MemCellType"
    CELL_AREA = "CellArea (F^2)"
    CELL_ASPECT_RATIO = "CellAspectRatio"
    ACCESS_TYPE = "AccessType"
    ACCESS_CMOS_WIDTH = "AccessCMOSWidth (F)"
    RESISTANCE_ON = "ResistanceOn (ohm)"
    RESISTANCE_OFF = "ResistanceOff (ohm)"
    READ_MODE = "ReadMode"
    READ_VOLTAGE = "ReadVoltage (V)"
    RESET_MODE = "ResetMode"
    RESET_CURRENT = "ResetCurrent (uA)"
    RESET_PULSE = "ResetPulse (ns)"
    SET_MODE = "SetMode"
    SET_CURRENT = "SetCurrent (uA)"
    SET_PULSE = "SetPulse (ns)"
    MEMORY_CELL_INPUT_FILE = "MemoryCellInputFile"
    DESIGN_TARGET = "DesignTarget"
    DEVICE_ROADMAP = "DeviceRoadmap"
    LOCAL_WIRE_TYPE = "LocalWireType"
    LOCAL_WIRE_REPEATER_TYPE = "LocalWireRepeaterType"
    LOCAL_WIRE_USE_LOW_SWING = "LocalWireUseLowSwing"
    GLOBAL_WIRE_TYPE = "GlobalWireType"
    GLOBAL_WIRE_REPEATER_TYPE = "GlobalWireRepeaterType"
    GLOBAL_WIRE_USE_LOW_SWING = "GlobalWireUseLowSwing"
    ROUTING = "Routing"
    INTERNAL_SENSING = "InternalSensing"
    TEMPERATURE = "Temperature (K)"
    BUFFER_DESIGN_OPTIMIZATION = "BufferDesignOptimization"
    PROCESS_NODE = "ProcessNode"
    OPTIMIZATION_TARGET = "OptimizationTarget"
    WORD_WIDTH = "WordWidth (bit)"
    CAPACITY = "Capacity (MB)"
    BENCHMARK_NAME = "Benchmark Name"
    READ_ACCESSES = "Read Accesses"
    WRITE_ACCESSES = "Write Accesses"
    TOTAL_DYNAMIC_READ_POWER = "Total Dynamic Read Power (mW)"
    TOTAL_DYNAMIC_WRITE_POWER = "Total Dynamic Write Power (mW)"
    TOTAL_POWER = "Total Power (mW)"
    TOTAL_DYNAMIC_READ_ENERGY = "Total Dynamic Read Energy (mJ)"
    TOTAL_DYNAMIC_WRITE_ENERGY = "Total Dynamic Write Energy (mJ)"
    TOTAL_ENERGY = "Total Dynamic Energy (mJ)"
    TOTAL_READ_ENERGY = "Total Dynamic Energy (mJ)"
    TOTAL_READ_LATENCY = "Total Read Latency (ms)"
    TOTAL_WRITE_LATENCY = "Total Write Latency (ms)"
    TOTAL_LATENCY = "Total Latency (ms)"
    READ_BW_UTIL = "Read BW Util"
    WRITE_BW_UTIL = "Write BW Util"
    AREA = "Area (mm^2)"
    AREA_EFFICIENCY = "Area Efficiency (percent)"
    READ_LATENCY = "Read Latency (ns)"
    WRITE_LATENCY = "Write Latency (ns)"
    READ_ENERGY = "Read Energy (pJ)"
    WRITE_ENERGY = "Write Energy (pJ)"
    LEAKAGE_POWER = "Leakage Power (mW)"
    BITS_PER_CELL = "Bits Per Cell"
    LIFE_EXPECTANCY = "Life Expectancy (s)"
