# Makefile

TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(shell pwd)/verilog_PEs/seizure_pipe.v
VERILOG_SOURCES += $(shell pwd)/verilog_PEs/spiral_fft_8192.v
TOPLEVEL = seizure_pipe
MODULE = test_fft_interface

include $(shell cocotb-config --makefiles)/Makefile.sim