name: PE tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Miniconda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        source $HOME/miniconda/bin/activate
        conda init bash
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda info -a  # Useful for debugging any issues with conda

    - name: Create conda environment
      run: |
        source $HOME/miniconda/bin/activate
        conda env create -f environment.yaml
        conda activate scalo_sim
        conda env list  # List environments to confirm activation

    - name: Run tests
      run: |
        source $HOME/miniconda/bin/activate
        conda activate scalo_sim
        conda list  # List installed packages to confirm numpy is installed
        cd ./asa/loader
        pytest
        cd ../fft/
        pytest
        cd ../bbf
        pytest
        cd ../pwxc
        pytest
        cd ../svm
        pytest
        cd ../thr
        pytest